language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - pip3 install coverage
install:
  - python3 setup.py install
  - pip3 install -r docs/requirements
script:
  - coverage run --source=ditto -m unittest discover -s tests -v
  - cd docs/
  - make html
  - cd -
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: docs/_build/html
  keep_history: true
  on:
    branch: master